name: tf-cd-lab1
on: [workflow_dispatch]
jobs:
  plan-and-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Get the code
      - uses: actions/checkout@v4
      # Setup terraform CLI
      - uses: hashicorp/setup-terraform@v2.0.3          
      # Init terraform
      - run: terraform -chdir=lab1 init -reconfigure
      # Run plan
      - run: terraform -chdir=lab1 plan
      # Run apply
      - run: terraform -chdir=lab1 apply -auto-approve
