name: tf-ci-lint-lab1
on: [push]
jobs:
  check-tf-fmt:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@v4
      # Setup terraform CLI
      - uses: hashicorp/setup-terraform@v2.0.3          
      # Run lint
      - run: terraform fmt -check -recursive lab1
