name: tf-destroy-lab1
on: [workflow_dispatch]
jobs:
  plan-and-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      # Get the code
      - uses: actions/checkout@v4
      # Setup terraform CLI
      - uses: hashicorp/setup-terraform@v2.0.3
      # Init terraform
      - run: terraform init -reconfigure
        working-directory: lab1
      # Run plan
      - run: terraform plan
        working-directory: lab1
      # Run destroy
      - run: terraform destroy -auto-approve
        working-directory: lab1
