name: check-tf-lint
on: [push]
jobs:
  check-tf-lint:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@v4
      # Setup terraform CLI
      - uses: hashicorp/setup-terraform@v2.0.3          
      # Run lint
      - run: terraform fmt -check -recursive lab1